imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ItrfWebsiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    bdgs_running_adress: 'http://sgn.ign.fr/bdgs/admin/workflow/api/run/%s/'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['SGNMaterialDesignInterfaceBundle:Form:material_design_layout.html.twig']
    globals:
        LAYOUT_FOSUser:     'SGNMaterialDesignInterfaceBundle:Dashboard:layout.html.twig'
        LAYOUT_UserManager: 'SGNMaterialDesignInterfaceBundle:Dashboard:layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: itrf
        connections:
            itrf:
                driver:   pdo_pgsql
                host:     "%database_host%"
                port:     5432
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            bdgs:
                driver:   pdo_pgsql
                host:     "%bdgs_database_host%"
                port:     5432
                dbname:   "%bdgs_database_name%"
                user:     "%bdgs_database_user%"
                password: "%bdgs_database_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        default_entity_manager:   itrf
        # auto_mapping: true
        entity_managers:
            itrf:
                connection:       itrf
                mappings:
                    FOSUserBundle: ~
                    SGNMaterialDesignInterfaceBundle: ~
            bdgs:
                connection:       bdgs
                mappings:
                    BDGSWorkflowBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SGN\MaterialDesignInterfaceBundle\Entity\User

sgn_material_design_interface:
    usermanager_role: ROLE_ITRF_USER_MANAGER
    administrated_roles:
        - { value: ROLE_ITRF_USER_MANAGER }
        - { value: ROLE_ITRF_MEMBER }
        - { value: ROLE_ADMIN }
        - { value: ROLE_SUPER_ADMIN }

bdgs_workflow:
    bdgs_running_adress: %bdgs_running_adress%
    orm: bdgs
