app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Les routes FOSUser (login, logout, change-password, register, ...)
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Les routes d'administration des utilisateurs
admin_user:
    resource: "@SGNMaterialDesignInterfaceBundle/Resources/config/routing/admin_users.yml"
    prefix:   /admin